### ISSUE TITLE
mnist.IdxDecodeError: Invalid IDX file, file empty or does not contain a full header

### ISSUE THREAD

**Issue by andrewschreiber** [datapythonista/mnist#19]
When running the code today, I got this issue. It persisted even when I uninstalled and reinstalled the `mnist` package. Issue continue when I created a new conda environment. Does not seem to happen on another computer.

```Traceback (most recent call last):
  File "/Users/andrew/.vscode/extensions/ms-python.python-2019.8.29288/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/Users/andrew/.vscode/extensions/ms-python.python-2019.8.29288/pythonFiles/lib/python/ptvsd/__main__.py", line 432, in main
    run()
  File "/Users/andrew/.vscode/extensions/ms-python.python-2019.8.29288/pythonFiles/lib/python/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/Users/andrew/anaconda3/envs/p36/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/Users/andrew/anaconda3/envs/p36/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Users/andrew/anaconda3/envs/p36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/andrew/git/numpy-saliency/main.py", line 9, in <module>
    train_images = np.int16(mnist.train_images())
  File "/Users/andrew/anaconda3/envs/p36/lib/python3.6/site-packages/mnist/__init__.py", line 161, in train_images
    return download_and_parse_mnist_file('train-images-idx3-ubyte.gz')
  File "/Users/andrew/anaconda3/envs/p36/lib/python3.6/site-packages/mnist/__init__.py", line 146, in download_and_parse_mnist_file
    return parse_idx(fd)
  File "/Users/andrew/anaconda3/envs/p36/lib/python3.6/site-packages/mnist/__init__.py", line 92, in parse_idx
    raise IdxDecodeError('Invalid IDX file, '
mnist.IdxDecodeError: Invalid IDX file, file empty or does not contain a full header.
```

Any recommendations?

**Comment by andrewschreiber** [comment]
Figured it out. The compressed `train-images-idx3-ubyte.gz` file had been corrupted (maybe changed internet connection during download, not exactly sure). One I deleted it, the file redownloaded and it worked. To find it, run in a Python interpreter:
```
import tempfile
print(tempfile.gettempdir())
```
Then go to that directory and delete `train-images-idx3-ubyte.gz`.

**Comment by datapythonista** [comment]
I think there was an issue previously about this, may be worth changing the error message to ask to remove the cached files. Will take care of it soon, since I'm planning some changes.
